import { Box, Button, Center, Flex, Text } from "@chakra-ui/react";

const WelcomeScreen = () => {
  return (
    <Box
      top="50%"
      left="50%"
      position="fixed"
      bg="orange.100"
      w="40%"
      transform="translate(-50%, -50%)"
      h="40%"
      borderRadius={15}
    >
      <Flex
        h="100%"
        flexDirection="column"
        alignItems="center"
        justifyContent="space-between"
      >
        <Text fontSize="3xl" mt="1.5rem">
          QUIZ
        </Text>
        <Text fontSize="2xl" mr="5rem" ml="5rem" bg="gray.300">
          Welcome at quiz! You can try yourself answering 10 hard questions
          generated by Trivia Database.
        </Text>
        <Button bg="green.300" w="20%" mb="1.5rem">
          START
        </Button>
      </Flex>
    </Box>
  );
};

export default WelcomeScreen;
